---
title: "Projektseminar 2022/23"
author: "Julius Klingelhoefer"
format: 
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    theme: 
      light: flatly
      dark: darkly
    smooth-scroll: true
---

## Anleitung

-   Unten finden Sie Links zu den Folien. Die Folien öffnen sich in einem neuen Tab.

-   Mit `F` können Sie den **Vollbild-Modus** aktivieren

-   Mit `E`, dann `STRG + P` können Sie die Folien drucken (am besten Querformat, ohne Rand).

## Aktuellster Foliensatz:

```{r}
#| echo: false
files = list.files("content")

slide = c()
for(i in 1:length(files))
{
  if(grepl("[0|1][0|1|2|3|4|5|6|7|8|9]", files[i]))
  {slide[i] = files[i]}
}

slide = max(slide)
```

<iframe style="width:100%; min-height:500px" src="`r paste0('/content/', slide, '/index.html')`">

</iframe>

## 01 Einführung/Willkommen zurück

Keine Quarto Slides - Siehe Teams für die Folien

## 02 Datenaufbereitung I

Folien für [Sitzung 02](content/02/index.html){target="_blank"}

## 03 Datenaufbereitung II

Folien für [Sitzung 03](content/03/index.html){target="_blank"}

## 04 Datenaufbereitung III

Folien für [Sitzung 04](content/04/index.html){target="_blank"}

## 05 Datenaufbereitung IV, Voraussetzungen

Folien für [Sitzung 05](content/05/index.html){target="_blank"}

<br>

<hr/>

### Impressum

::: {.callout-note collapse="true"}
#### Impressum

##### Angaben gemäß § 5 TMG

<p>Julius Klingelhoefer<br /> Findelgasse 7/9<br /> 90402 Nürnberg</p>

##### Kontakt

<p>Telefon: +499115302-95671<br /> E-Mail: julius.klingelhoefer\[ - at - \]fau.de</p>

<p>Quelle: <a href="https://www.e-recht24.de">e-recht24.de</a></p>
:::

### Credit

Vielen Dank an [Christoph Adrian](https://github.com/chrdrn/) für das Bereitstellen einer früheren Version der R-Inhalte dieses Kurses.
